name: Deploy to Azure VM

on:
  push:
    branches:
      - master

  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, zip, mysql, bcmath, gd
          tools: composer

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Install NPM
        run: npm install

      - name: Building React Asset
        run: npm run build

      - name: making .env
        run: echo "${{ secrets.DOT_ENV }}" > .env

      - name: Menyinkronkan File ke Server (AEnterprise)
        uses: AEnterprise/rsync-deploy@v1.0.2
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SERVER_IP: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_PORT: "22"
          FOLDER: "./"
          SERVER_DESTINATION: "/var/www/mona"
          EXCLUDE: ".git/,.github/,node_modules/"
          
      - name: Run deployment script
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash ~/deploy.sh
